spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:voting
#    tcp: jdbc:h2:tcp://localhost:9092/mem:voting
#    url: jdbc:h2:/Users/fuat/IdeaProjects/voting_system/db
#    tcp: jdbc:h2:tcp://localhost:9092/Users/fuat/IdeaProjects/voting_system/db
    username: sa
    password:

  h2:
    console:
      enabled: true

  cache:
    cache-names: users
    caffeine:
      spec: maximumSize=5000,expireAfterAccess=60s

  data:
    rest:
      base-path: /api
      return-body-on-create: true
      default-page-size: 20

#  security:
#    user:
#      name: user
#      password: password
#      roles: USER

logging:
  level:
    root: warn
    com.example.voting_system: debug
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
