spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:voting
    #tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    #url: jdbc:h2:/Users/fuat/IdeaProjects/voting_system/db
    #tcp: jdbc:h2:tcp://localhost:9092/Users/fuat/IdeaProjects/voting_system/db
    username: sa
    password:
  h2:
    console:
      enabled: true